version: 1.0.{build}
image:
- Visual Studio 2017
branches:
  only:
  - master
configuration: Release
platform:
- Win32
- x64
matrix:
  fast_finish: true
build:
  parallel: true
  verbosity: minimal
after_build:
- ps: >-
    7z a __dep.zip -r *.h

    7z a __dep.zip -r *dlfcn.c

    7z a __dep.zip -r *.lib

    7z a __dep.zip -r *.dll

    7z a __dep.zip -r *.pdb
test: off
deploy: off
artifacts:
- path: __dep.zip
on_success:
- ps: >-
    $token = $env:API_TOKEN

    $headers = @{ "Authorization" = "Bearer $token"}

    $body = @{accountName = $env:API_NAME; projectSlug = "objectivelymvc"}

    $bodyAsJson = $body | ConvertTo-json

    if ($env:Platform -Match "x64") {

    Invoke-Restmethod -uri 'https://ci.appveyor.com/api/builds' -Headers $headers -Method Post -Body $bodyAsjson -ContentType "application/json"

    }