version: 1.0.{build}
branches:
  only:
  - feature/vs-ci
configuration: Release
platform:
- Win32
- x64
init:
- ps: 
install:
- ps: >-
    Push-Location "Objectively.vs15\"

    [Environment]::CurrentDirectory = $PWD

    .\PREPARE_ALL.ps1

    Pop-Location

    [Environment]::CurrentDirectory = $PWD
build:
  parallel: true
  verbosity: minimal
test: off